# Generated by Django 2.2.7 on 2020-08-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('cfu_number', models.PositiveIntegerField(default=6)),
                ('done', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=300)),
                ('next_date', models.DateTimeField()),
            ],
        ),
    ]
