# Generated by Django 2.2.7 on 2020-08-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(max_length=4000)),
                ('subject', models.ForeignKey(on_delete=True, related_name='exam', to='dashboard.Exam')),
            ],
        ),
    ]
