# Generated by Django 2.2.7 on 2020-08-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='last_updated',
            new_name='date',
        ),
    ]
