# Generated by Django 2.2.7 on 2020-08-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200801_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
